name: ShinHyeong's Dev Log
description: about Computer Science 
meta_description: "ShinHyeong's Dev Log, about Computer Science "

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /kasper
domain_name: "http://shinhyeong.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "ShinHyeong"

# Disqus config
disqus-shortname: ""
